name: dziardziel_com
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^1.0.4
  google_fonts: ^1.1.0
  url_launcher: ^5.5.0
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/banner/
    - assets/coffeeBook/
    - assets/eGalileo/
    - assets/footer/
    - assets/navBar/
    - assets/PayR/
    - assets/technologies/
